global:
  marketplace-ami: false
  owner: jmmccon@amazon.com
  qsname: quickstart-git2s3
  regions:
    - us-east-1
  reporting: true
 
tests:
  defaults:
    parameter_input: quickstart-git2s3-defaults.json
    template_file: quickstart-git2s3.template
